# Generated by Django 4.2.4 on 2023-08-15 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_playlist_song_song_id_user_playlist_songs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='play_list',
            new_name='playlist',
        ),
    ]
