# Generated by Django 4.2.4 on 2023-08-15 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_alter_user_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='playlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='src.playlist'),
        ),
    ]
