# Generated by Django 4.2.4 on 2023-08-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_alter_user_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='essentiaproperties',
            name='key',
            field=models.CharField(default='undefined', max_length=200),
            preserve_default=False,
        ),
    ]
