# Generated by Django 4.2.4 on 2023-09-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_essentiaproperties_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='essentiaproperties',
            name='danceability',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='essentiaproperties',
            name='energy',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='essentiaproperties',
            name='key_scale_strength',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='essentiaproperties',
            name='scale',
            field=models.CharField(default='None', max_length=200),
            preserve_default=False,
        ),
    ]
