# Generated by Django 4.2.4 on 2023-09-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_essentiaproperties_danceability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essentiaproperties',
            name='bpm',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='essentiaproperties',
            name='danceability',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='essentiaproperties',
            name='energy',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='essentiaproperties',
            name='key_scale_strength',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.FloatField(),
        ),
    ]
