# Generated by Django 4.2.4 on 2023-09-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_alter_essentiaproperties_bpm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='essentiaproperties',
            name='cuepoint_in',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='essentiaproperties',
            name='cuepoint_out',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
