# Generated by Django 4.2.4 on 2023-09-14 08:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0009_essentiaproperties_cuepoint_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='essentiaproperties',
            name='moods',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), default=[''], size=8),
            preserve_default=False,
        ),
    ]
