# Generated by Django 4.2.4 on 2023-09-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0010_essentiaproperties_moods'),
    ]

    operations = [
        migrations.AddField(
            model_name='essentiaproperties',
            name='loudness',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
