# Generated by Django 4.2.4 on 2023-09-21 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0011_essentiaproperties_loudness'),
    ]

    operations = [
        migrations.CreateModel(
            name='Similarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.FloatField()),
                ('song_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_1', to='src.song')),
                ('song_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_2', to='src.song')),
            ],
        ),
    ]
