# Generated by Django 4.2.4 on 2023-09-21 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0012_similarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essentiaproperties',
            name='song',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='src.song'),
        ),
    ]
