# Generated by Django 4.2.4 on 2023-09-22 12:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0015_playlist_order_alter_user_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
    ]
